name: rocmlm
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - seaborn
  - matplotlib
  - gitpython
  - pyyaml
  - tqdm
  - opencv
  - tabulate
