name: rocmlm2
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - seaborn
  - matplotlib
  - gitpython
  - pyyaml
  - pyqt
  - tqdm
  - opencv
  - tabulate
  - pytorch
  - torchvision
  - torchaudio
